### ISSUE TITLE
No swagger in Google Colab

### ISSUE THREAD

**Issue by cboyda** [weatherapicom/python#2]
Always curious to see new methods for API calls.
`!pip install swagger_client` results in
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement swagger_client (from versions: none)
ERROR: No matching distribution found for swagger_client

Why not demonstrate functionality in python with `requests.get` ?

**Comment by adriangalilea** [comment]
Hello, they didn't publish it on pipy so you need to manually input the url when doing `pip install url_here`

They should at least fix the readme :)

**Comment by weatherapicom** [comment]
Where exactly do we need to add this information?

**Comment by weatherapicom** [comment]
We have fixed it now.
