### ISSUE TITLE
No Condition Text

### ISSUE THREAD

**Issue by Shades-of-Dark** [weatherapicom/python#3]
when using this request: http://api.weatherapi.com/v1/forecast.json?key={weather_api_key}&q=Sunnyvale&days=2&aqi=no&alerts=no

I'm trying to get the condition text yet it is an empty dict for the current day. The reason I use forecast.json instead of current.json is because later I get the forecast so getting both in one request is easier.

**Comment by weatherapicom** [comment]
It seems you may have disabled the response field.

You may enable the response fields by logging into your account and then going to the Response Fields section (https://www.weatherapi.com/my/fields.aspx) to choose which field to return in the API response.
