### ISSUE TITLE
Inconsistent Project Name Error During Installation via pip

### ISSUE THREAD

**Issue by theangryhobbit** [weatherapicom/python#4]
### Description:
**Issue Summary:**
When attempting to install the weatherapipython package from the GitHub repository https://github.com/weatherapicom/python.git using pip, an inconsistency in project naming leads to installation failure.

### Steps to Reproduce:
Run the installation command: sudo pip3 install git+https://github.com/weatherapicom/python.git#egg=weatherapipython.
Encounter an error related to project name inconsistency.
**Expected Behavior:**
The package should be installed successfully without any name mismatch issues.

**Actual Behavior:**
The installation process fails with the following error message:

`Discarding git+https://github.com/weatherapicom/python.git#egg=weatherapipython: Requested swagger-client from git+https://github.com/weatherapicom/python.git#egg=weatherapipython has inconsistent name: expected 'weatherapipython', but metadata has 'swagger-client'`
`ERROR: Could not find a version that satisfies the requirement weatherapipython (unavailable) (from versions: none)`
`ERROR: No matching distribution found for weatherapipython (unavailable)`

This suggests a mismatch between the specified project name in the pip command (weatherapipython) and the actual project name in the package metadata (swagger-client).

### Additional Context:
This issue occurred while attempting to install directly from the GitHub repository.
Swagger-client seems to be the correct project name to use for installation, since it's used in the `setup.py` file to describe the project.

### Concrete action
Correct the readme to use the correct project name in the pip installation guide.

**Comment by Gankcore** [comment]
I have the same error as above.

**Comment by dinuka125** [comment]
I faced the same issue mentioned above ,  following worked for me  👇🏻        
`pip install git+https://github.com/weatherapicom/python.git#egg=swagger-client`
